apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-main
  namespace: monitoring
  labels:
    alertmanager: main
    app.kubernetes.io/name: alertmanager
type: Opaque
stringData:
  alertmanager.yaml: |
    global:
      smtp_smarthost: 'smtp.gmail.com:587'
      smtp_from: 'manageralert8@gmail.com'
      smtp_auth_username: 'manageralert8@gmail.com'
      smtp_auth_password: 'alert_alert'
      smtp_require_tls: true

    route:
      receiver: me
      group_wait: 10s
      group_interval: 30s
      repeat_interval: 30m
      routes:
        # Route for critical alerts
        - match:
            severity: critical
          receiver: critical_alerts

        # Route for warning alerts
        - match:
            severity: warning
          receiver: warning_alerts

        # Route for informational alerts
        - match:
            severity: info
          receiver: info_alerts

    receivers:
      - name: me
        email_configs:
          - to: 'adhambasheir000@gmail.com'

      - name: critical_alerts
        email_configs:
          - to:
            - 'danielfarag146@gmail.com'
            - 'philopater.mansour.gerais@gmail.com'
            - 'philopater.mansour@gmail.com'
            - 'seifhendawy1@gmail.com'
            - 'SivoM86@gmail.com'
            - 'amrbaghdad@gmail.com'
            - 'zyad.ashraf1998@gmail.com'

      - name: warning_alerts
        email_configs:
          - to:
            - 'danielfarag146@gmail.com'
            - 'philopater.mansour.gerais@gmail.com'
            - 'philopater.mansour@gmail.com'

      - name: info_alerts
        email_configs:
          - to:
            - 'seifhendawy1@gmail.com'
            - 'SivoM86@gmail.com'
            - 'zyad.ashraf1998@gmail.com'
