apiVersion: v1
kind: Service
metadata:
  name: prometheus-backend-service
  # namespace: random-choice
  labels:
    app: backend-node
spec:
  selector:
    app: backend-node
  ports:
    - name: metrics
      port: 8080
      # targetPort: 3000
