apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: posts-api-alerts
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
    role: alert-rules
spec:
  groups:
    - name: posts-api-alerts
      rules:
        # High request rate alert
        - alert: HighPostsAPIRequestRate
          expr: sum(rate(posts_api_requests_total[1m])) * 60 > 100
          for: 1m
          labels:
            severity: warning
          annotations:
            summary: "High /posts request rate"
            description: |
              The /posts endpoint received more than 100 requests in the last 1 minute.

        # High failure rate alert
        - alert: HighPostsAPIFailureRate
          expr: sum(rate(posts_api_failures_total[1m])) / sum(rate(posts_api_requests_total[1m])) > 0.5
          for: 1m
          labels:
            severity: critical
          annotations:
            summary: "High failure rate for /posts"
            description: |
              More than 50% of requests to /posts failed in the last 1 minute.

        # Low request rate alert
        - alert: LowPostsAPIRequestRate
          expr: sum(rate(posts_api_requests_total[1m])) * 60 < 5
          for: 1m
          labels:
            severity: info
          annotations:
            summary: "Low /posts request rate"
            description: |
              The /posts endpoint received fewer than 5 requests in the last 1 minute.

        # No requests alert
        - alert: NoPostsAPIRequests
          expr: sum(rate(posts_api_requests_total[1m])) * 60 < 1
          for: 1m
          labels:
            severity: critical
          annotations:
            summary: "No requests to /posts"
            description: |
              The /posts endpoint received no requests in the last 1 minute.
