replicaCount: 1
name: redis

image:
  repository: docker.io/redis
  tag: latest


service: 
  name: redis

resources:
  limits:
    cpu: 300m
    memory: 512Mi
  requests:
    cpu: 50m
    memory: 128Mi

secret:
  name: redis-k8s-secret

storageClassName: "ebs-csi"
