replicaCount: 1
name: frontend
image:
  repository: 730335506473.dkr.ecr.us-east-1.amazonaws.com/frontend
  tag: 30bfab706aac4ddd43082d3276416c7cfa532792
resources:
  limits:
    cpu: 50m
    memory: 32Mi
  requests:
    cpu: 50m
    memory: 32Mi
service:
  backend:
    name: backend-service
    port: 3000
  frontend:
    name: frontend-service
    type: ClusterIP
    port: 80
    targetPort: 80
config:
  name: nginx-config
