apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.name }}
  serviceName: {{ .Values.service.name }}-headless
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
      - name: {{ .Values.name }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        args: ["--requirepass", "$(REDIS_PASSWORD)"]
        ports:
        - containerPort: 6379
          name: {{ .Values.name }}
        envFrom:
        - secretRef:
            name: {{ .Values.secret.name }}
            
        volumeMounts:
        - name: {{ .Values.name }}-pvc
          mountPath: /data

  volumeClaimTemplates:
  - metadata:
      name: {{ .Values.name }}-pvc
    spec:
      storageClassName: {{ .Values.storageClassName }}
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi