# TO BE DELETED [ secret manager ]
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
type: Opaque
stringData:
  REDIS_HOST: {{ .Values.service.name }}
  REDIS_PASSWORD: password
  REDIS_DB: "0"