apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.frontend.name }}
spec:
  type: {{ .Values.service.frontend.type }}
  selector:
    app: {{ .Values.name }}
  ports:
  - protocol: TCP
    port: {{ .Values.service.frontend.port }}
    targetPort: {{ .Values.service.frontend.targetPort }}
    {{- if .Values.service.frontend.nodePort }}
    nodePort: {{ .Values.service.frontend.nodePort }}
    {{- end }}