ingress:
  name: app-ingress
  namespace: default
  class: nginx
  clusterIssuer: letsencrypt
  host: app.danielfarag.cloud
  tlsSecret: app-tls

  paths:
    - path: /
      service: frontend-service
      port: 80
    - path: /posts
      service: backend-service
      port: 3000
