ingress:
  name: app-ingress
  namespace: default
  class: nginx
  # clusterIssuer: letsencrypt
  host: app.itilabs.net
  # tlsSecret: iticpd-tls-secret

  paths:
    - path: /
      service: frontend-service
      port: 80
    - path: /api
      service: backend-service
      port: 3000
    - path: /mysql
      service: mysql
      port: 3306
    - path: /redis
      service: redis
      port: 6379