controller:
  serviceType: LoadBalancer
  servicePort: 80
  admin:
    password: password
  installPlugins:
    - workflow-aggregator
    - kubernetes
    - github

persistence:
  enabled: true
  storageClass: ebs-csi
  size: 3Gi
  accessMode: ReadWriteOnce