name: backend-node
replicaCount: 1
image:
  repository: 478614263566.dkr.ecr.us-east-1.amazonaws.com/backend
  tag: "473947301d3172fc568a0abbc245eef5a6ec8d39"
service:
  name: backend-service
  type: ClusterIP
  port: 3000
  targetPort: 3000
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi
secret:
  mysql: mysql-k8s-secret
  redis: redis-k8s-secret
