name: Build Backend Image [ Testing ]

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Print Hello World
      run: echo "Hello World!"
