name: Deploy infra

on:
  push:
    branches:
      - main
    paths:
      - 'terraform/infra/**'

jobs:
  infra:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Process Infra
      run: echo "Process infra!"
