name: Deploy platform

on:
  push:
    branches:
      - main
    paths:
      - 'terraform/platform/**'

jobs:
  platform:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Process Platform
      run: echo "Process platform!"
